server:
  port: 8900
logging:
  level:
    org.mooc: debug
spring:
  application:
    name: microservice-provider-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-demo?useSSL=false
    username: root
    password: root
    druid:
      initial-size: 5
      max-active: 20
      # ��ȡ�������ȴ�ʱ�䣬��λ ����
      max-waite: 60000
      # �Ƿ��� PSCache��mysql �½���ر�
      pool-prepared-statements: false
      # �������0 �Ὺ�� PSCached������ pool-prepared-statements ������
      max-pool-prepared-statement-per-connection-size: -1
      # ��������Ƿ���Ч�� sql���粻������
      validation-query: select 'x'
      # ��������Ƿ���Ч�ĳ�ʱʱ��
      validation-query-timeout: 60000
      # ��������ʱִ�� validation-query ��������Ƿ���Ч���ή������
      test-on-borrow: false
      # �黹����ʱִ�� validation-query ��������Ƿ���Ч����Ӱ������
      test-on-return: false
      # ��������ʱ��⣬�������ʱ����� time-between-eviction-runs-millis��ִ�� validation-query ��������Ƿ���Ч
      # ����Ӱ�����ܣ����鿪��
      test-while-idle: true
      # ���������壺
      # Destroy�̻߳������ӵļ��ʱ�䣬������ӿ���ʱ����ڵ���minEvictableIdleTimeMillis��ر���������
      # testWhileIdle���ж����ݣ���ϸ��testWhileIdle���Ե�˵��
      # Ĭ�� 1 ����
      time-between-eviction-runs-millis: 60000
      # ���ӱ��ֿ��ж������������Сʱ��
      min-evictable-idle-time-millis: 100000
      # �����������ַ�����ͨ�������ķ�ʽ������չ���
      # ���ͳ���õ�filter:stat
      # ��־�õ�filter:log4j
      # filter:wall
      filters: stat,log4j,wall


mybatis:
  config-location: classpath:mybatis.cfg.xml
  type-aliases-package: org.mooc.springcloud.entity
  mapper-locations:
    - classpath:mapper/*.xml
